"""empty message

Revision ID: 24f600b5e4cd
Revises: 59783ca45808
Create Date: 2014-10-07 16:19:15.549045

"""

# revision identifiers, used by Alembic.
revision = '24f600b5e4cd'
down_revision = '59783ca45808'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #adjusted so historical table not removed.
    op.add_column('historical', sa.Column('added', sa.VARCHAR()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #adjusted so only the column is dropped.
    op.drop_column('historical', 'added')
    ### end Alembic commands ###
