"""empty message

Revision ID: 59783ca45808
Revises: None
Create Date: 2014-09-26 13:42:22.190014

"""

# revision identifiers, used by Alembic.
revision = '59783ca45808'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'version')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical')
    ### end Alembic commands ###
