"""empty message

Revision ID: 8f57e60954b
Revises: None
Create Date: 2014-09-24 11:40:15.606183

"""

# revision identifiers, used by Alembic.
revision = '8f57e60954b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical')
    ### end Alembic commands ###
